import {useEffect,useState} from 'react';
import {ActivityIndicator,FlatList,Image,KeyboardAvoidingView,Linking,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import * as Crypto from 'expo-crypto';
import {ApiClient} from '@banana/api-client';
import {Outbox,cacheKey,type CacheAdapter} from '@banana/chat-core';
import type {LoginResult,Membership,Page,Room,Message} from '@banana/shared';

const api=new ApiClient(process.env.EXPO_PUBLIC_API_URL??'http://127.0.0.1:8000/api/v1',{get:()=>SecureStore.getItemAsync('refresh_token'),set:async token=>token?SecureStore.setItemAsync('refresh_token',token):SecureStore.deleteItemAsync('refresh_token')});
api.app={platform:Platform.OS==='ios'?'ios':'android',version:'0.1.0'};
class SecureCache implements CacheAdapter {async read<T>(key:string){const value=await SecureStore.getItemAsync('cache:'+key);return value?JSON.parse(value) as T:null;}async write<T>(key:string,value:T){await SecureStore.setItemAsync('cache:'+key,JSON.stringify(value));}async clear(){for(const key of ['rooms','messages','outbox'])await SecureStore.deleteItemAsync('cache:'+key);}}
const cache=new SecureCache();
export default function Home(){
 const [auth,setAuth]=useState<LoginResult|null>(null);const [workspaces,setWorkspaces]=useState<Membership[]>([]);const [workspace,setWorkspace]=useState<Membership|null>(null);const [rooms,setRooms]=useState<Room[]>([]);const [room,setRoom]=useState<Room|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [queued,setQueued]=useState(0);
 useEffect(()=>{void (async()=>{try{if(await SecureStore.getItemAsync('refresh_token')){await api.tokens.refresh();const list=await api.get<Membership[]>('/me/workspaces');setWorkspaces(list);setWorkspace(list[0]??null);if(list[0]){api.workspaceId=list[0].workspace.id;const key=cacheKey('me',list[0].workspace.id,'rooms');const saved=await cache.read<Room[]>(key);if(saved)setRooms(saved);const fresh=(await api.raw<Page<Room>>('/rooms')).data;setRooms(fresh);await cache.write(key,fresh);}}}catch{await api.tokens.clear();}})();},[]);
 useEffect(()=>{if(!workspace)return;api.workspaceId=workspace.workspace.id;void (async()=>{const key=cacheKey('me',workspace.workspace.id,'rooms');const saved=await cache.read<Room[]>(key);if(saved)setRooms(saved);try{const fresh=(await api.raw<Page<Room>>('/rooms')).data;setRooms(fresh);await cache.write(key,fresh);}catch{}})();},[workspace?.workspace.id]);
 useEffect(()=>{if(!room||!workspace)return;const key=cacheKey('me',workspace.workspace.id,'room:'+room.id);const refresh=async()=>{try{const fresh=(await api.raw<Page<Message>>('/rooms/'+room.id+'/messages')).data;setMessages(fresh);await cache.write(key,fresh);}catch{}};void cache.read<Message[]>(key).then(saved=>saved&&setMessages(saved));void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[room?.id,workspace?.workspace.id]);
 const signIn=async()=>{setBusy(true);setError('');try{const data=await api.request<LoginResult>('/auth/login',{method:'POST',body:JSON.stringify({username,password,device:{platform:Platform.OS==='ios'?'ios':'android',name:'Expo mobile',app_version:'0.1.0'}})},false);await api.tokens.set(data);setAuth(data);setWorkspaces(data.workspaces);const ws=data.workspaces[0]??null;setWorkspace(ws);if(ws){api.workspaceId=ws.workspace.id;setRooms((await api.raw<Page<Room>>('/rooms')).data);}}catch(e){setError(e instanceof Error?e.message:'Sign in failed');}finally{setBusy(false);}};
 const send=async()=>{if(!room||!workspace||!draft.trim())return;const body=draft;const id=Crypto.randomUUID();setDraft('');const key=cacheKey('me',workspace.workspace.id,'outbox');const box=new Outbox<{body:string;client_message_id:string}>(cache,key,item=>api.post('/rooms/'+item.roomId+'/messages',item.payload).then(()=>{}));await box.load();try{await api.post('/rooms/'+room.id+'/messages',{body,client_message_id:id});setMessages((await api.raw<Page<Message>>('/rooms/'+room.id+'/messages')).data);await box.flush();setQueued(box.values().length);}catch(e){await box.enqueue({id,roomId:room.id,createdAt:Date.now(),payload:{body,client_message_id:id}});setQueued(box.values().length);setError('Offline — message queued');}};
 if(!workspace)return <SafeAreaView style={styles.login}><View style={styles.logo}><Text style={styles.logoGlyph}>◒</Text></View><Text style={styles.title}>Banana Chat</Text><Text style={styles.subtitle}>Good things happen together.</Text><TextInput style={styles.input} autoCapitalize="none" autoComplete="username" placeholder="Username" value={username} onChangeText={setUsername}/><TextInput style={styles.input} secureTextEntry autoComplete="current-password" placeholder="Password" value={password} onChangeText={setPassword}/>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable style={styles.primary} disabled={busy} onPress={()=>void signIn()}><Text style={styles.primaryText}>{busy?'Signing in…':'Sign in'}</Text></Pressable></SafeAreaView>;
 if(room)return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={()=>setRoom(null)}><Text style={styles.back}>‹ Rooms</Text></Pressable><Text style={styles.headerTitle}>{room.name??room.other_user?.display_name}</Text></View><FlatList data={messages} keyExtractor={m=>m.id} contentContainerStyle={styles.messages} renderItem={({item})=>item.type==='system'?<Text style={styles.system}>✳ {item.system_event?.kind.replaceAll('_',' ')}</Text>:<View style={[styles.bubble,item.sender?.id===auth?.user.id&&styles.own]}><Text style={styles.sender}>{item.sender?.display_name}</Text><Text style={styles.message}>{item.deleted_at?'This message was deleted':item.body}</Text>{item.attachments.map(a=>a.kind==='image'?<Pressable key={a.id} onPress={()=>void Linking.openURL(a.urls.original)}><Image source={{uri:a.urls.thumb_md??a.urls.original}} style={styles.attachment}/></Pressable>:<Pressable key={a.id} onPress={()=>void Linking.openURL(a.urls.original)}><Text style={styles.file}>📎 {a.original_name}</Text></Pressable>)}</View>}/>{queued>0?<Text style={styles.queue}>{queued} message(s) waiting to send</Text>:null}<View style={styles.composer}><TextInput style={styles.composeInput} multiline placeholder="Write a message…" value={draft} onChangeText={setDraft}/><Pressable style={styles.send} onPress={()=>void send()}><Text>↑</Text></Pressable></View></SafeAreaView></KeyboardAvoidingView>;
 return <SafeAreaView style={styles.screen}><View style={styles.header}><View><Text style={styles.eyebrow}>{workspace.workspace.name}</Text><Text style={styles.headerTitle}>Messages</Text></View></View>{workspaces.length>1?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.workspaceTabs}>{workspaces.map(item=><Pressable key={item.workspace.id} style={[styles.workspaceTab,item.workspace.id===workspace.workspace.id&&styles.workspaceTabActive]} onPress={()=>{setRoom(null);setWorkspace(item);}}><Text>{item.workspace.name}</Text>{item.unread_rooms_count>0?<Text style={styles.badge}>{item.unread_rooms_count}</Text>:null}</Pressable>)}</ScrollView>:null}<FlatList data={rooms} keyExtractor={r=>r.id} contentContainerStyle={styles.rooms} ListEmptyComponent={<Text style={styles.empty}>A little quiet here. Start a conversation on the web.</Text>} renderItem={({item})=><Pressable style={styles.room} onPress={()=>setRoom(item)}><View style={styles.roomIcon}><Text>#</Text></View><View style={styles.roomCopy}><Text style={styles.roomName}>{item.name??item.other_user?.display_name}</Text><Text numberOfLines={1} style={styles.preview}>{item.last_message?.body??'This is the beginning of something good.'}</Text></View>{item.unread_count>0?<Text style={styles.badge}>{item.unread_count}</Text>:null}</Pressable>}/></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#fff'},login:{flex:1,justifyContent:'center',padding:32,backgroundColor:'#f8f9f5'},logo:{width:56,height:56,borderRadius:18,backgroundColor:'#f4d35a',alignItems:'center',justifyContent:'center',marginBottom:22},logoGlyph:{fontSize:30,color:'#354131'},title:{fontSize:31,fontWeight:'700',color:'#354131'},subtitle:{fontSize:14,color:'#8b9580',marginTop:10,marginBottom:35},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dfe5d5',padding:15,borderRadius:10,marginBottom:13},primary:{backgroundColor:'#f4d35a',padding:16,borderRadius:10,alignItems:'center',marginTop:7},primaryText:{fontWeight:'700',color:'#423f2b'},error:{color:'#b65d4b',marginVertical:8},header:{minHeight:78,paddingHorizontal:22,paddingVertical:15,borderBottomWidth:1,borderBottomColor:'#eceee9',justifyContent:'center'},headerTitle:{fontSize:20,fontWeight:'700',color:'#354131'},eyebrow:{fontSize:10,color:'#939f82',textTransform:'uppercase',letterSpacing:1,marginBottom:4},back:{color:'#71845d',marginBottom:6},workspaceTabs:{paddingHorizontal:14,paddingVertical:8,gap:8},workspaceTab:{flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:12,paddingVertical:8,borderRadius:14,backgroundColor:'#f2f5eb'},workspaceTabActive:{backgroundColor:'#f4d35a'},rooms:{padding:14},room:{flexDirection:'row',alignItems:'center',padding:14,borderRadius:12,marginBottom:5},roomIcon:{height:42,width:42,borderRadius:13,backgroundColor:'#eef2e6',alignItems:'center',justifyContent:'center'},roomCopy:{flex:1,marginHorizontal:13},roomName:{fontWeight:'600',fontSize:14,color:'#465340'},preview:{color:'#98a18f',fontSize:12,marginTop:5},badge:{backgroundColor:'#c5a956',color:'#fff',borderRadius:8,paddingHorizontal:7,paddingVertical:3,fontSize:10},empty:{textAlign:'center',color:'#98a18f',padding:50,lineHeight:22},messages:{padding:18,gap:12},bubble:{alignSelf:'flex-start',maxWidth:'84%',backgroundColor:'#f2f5eb',padding:12,borderRadius:13},own:{alignSelf:'flex-end',backgroundColor:'#f8f1d5'},sender:{fontSize:10,fontWeight:'700',color:'#7d8d68',marginBottom:5},message:{fontSize:14,color:'#56634d',lineHeight:20},attachment:{width:220,height:160,borderRadius:10,marginTop:8},file:{color:'#667759',fontWeight:'600',marginTop:8},queue:{textAlign:'center',fontSize:12,color:'#8b6f20',padding:6,backgroundColor:'#fff8d8'},system:{fontSize:11,color:'#9da890',textAlign:'center',marginVertical:8},composer:{flexDirection:'row',gap:10,padding:13,borderTopWidth:1,borderTopColor:'#eceee9'},composeInput:{flex:1,maxHeight:110,borderWidth:1,borderColor:'#dfe5d5',borderRadius:12,paddingHorizontal:14,paddingVertical:11},send:{width:43,height:43,borderRadius:12,backgroundColor:'#f4d35a',alignItems:'center',justifyContent:'center'}});
