import {useCallback,useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {Archive,Brain,Check,Copy,Plus,Send,Sparkles,Square,Trash2,X} from 'lucide-react';
import type {AiConversation,AiMessage} from '@banana/shared';
import {api,useSession} from './state';
import {IconButton,Modal,Spinner} from './components';

interface AiStatus {enabled:boolean;configured:boolean;allowed_in_workspace:boolean;provider:{name:string;model:string;window_size:number}|null;limits:{daily_messages:number;max_message_chars:number};usage_today:{messages:number};memory_enabled:boolean;consented:boolean;admin_review:boolean}
interface Memory {id:string;content:string;category:'profile'|'preference'|'project'|'other';importance:number}
export function AiPane({report}:{report:(error:unknown)=>void}) {
 const {t}=useTranslation();const {workspaceId}=useSession();const query=useQueryClient();const [active,setActive]=useState<string|null>(null);const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [memory,setMemory]=useState(false);const [deleteConversation,setDeleteConversation]=useState<AiConversation|null>(null);const bottom=useRef<HTMLDivElement>(null);
 const {data:status,isPending:loadingStatus}=useQuery({queryKey:['ai','status',workspaceId],queryFn:()=>api.get<AiStatus>('/ai/status')});
 const {data:conversations=[]}=useQuery({queryKey:['ai','conversations',workspaceId],queryFn:()=>api.get<AiConversation[]>('/ai/conversations'),enabled:!!status?.configured});
 useEffect(()=>{if(active&&!conversations.some(c=>c.id===active))setActive(null);},[conversations,active]);
 const {data:messages=[],isPending:loadingMessages}=useQuery({queryKey:['ai','messages',workspaceId,active],queryFn:()=>api.get<AiMessage[]>('/ai/conversations/'+active+'/messages'),enabled:!!active,refetchInterval:q=>q.state.data?.some(m=>['pending','streaming'].includes(m.status))?1500:false});
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[messages]);
 const refresh=()=>{void query.invalidateQueries({queryKey:['ai']});};
 const create=async()=>{try{const {conversation}=await api.post<{conversation:AiConversation}>('/ai/conversations',{});setActive(conversation.id);refresh();}catch(e){report(e);}};
 const send=async()=>{if(!active||!draft.trim()||busy)return;setBusy(true);const content=draft;setDraft('');try{await api.post('/ai/conversations/'+active+'/messages',{content,client_message_id:crypto.randomUUID()});refresh();}catch(e){setDraft(content);report(e);}finally{setBusy(false);}};
 const consent=async()=>{try{await api.post('/ai/consent');refresh();}catch(e){report(e);}};
 if(loadingStatus)return <Spinner/>;
 if(!status?.enabled||!status.allowed_in_workspace)return <div className="ai-empty"><span className="ai-emblem"><Sparkles size={34}/></span><h2>{t('assistant')}</h2><p>{t('aiHint')}</p></div>;
 if(!status.configured)return <div className="ai-empty"><span className="ai-emblem"><Sparkles size={34}/></span><h2>{t('aiNotConfigured')}</h2><p>{t('aiNotConfiguredHint')}</p></div>;
 return <div className="ai-page"><aside className="ai-conversations"><button className="primary" onClick={()=>void create()}><Plus size={15}/>{t('newAi')}</button>{conversations.map(c=><div className={'ai-conversation '+(c.id===active?'selected':'')} key={c.id}><button onClick={()=>setActive(c.id)}>{c.title??t('newAi')}</button><IconButton label={t('delete')} onClick={()=>setDeleteConversation(c)}><Trash2 size={13}/></IconButton></div>)}</aside><section className="ai-chat">
  <header className="chat-header"><span className="ai-icon"><Sparkles size={20}/></span><div className="chat-title"><h1>{conversations.find(c=>c.id===active)?.title??t('assistant')}</h1><span>{status.provider?.name} · {status.provider?.model} · {status.usage_today.messages}/{status.limits.daily_messages}</span></div><div className="ai-header-actions"><IconButton label={t('memory')} onClick={()=>setMemory(true)}><Brain size={19}/></IconButton></div></header>
  {!status.consented?<div className="ai-empty"><span className="ai-emblem"><Sparkles size={35}/></span><h2>{t('aiPrivate')}</h2><p>{t('aiHint')}</p><div className="ai-disclosure"><p>{t('aiConsent')}</p><button className="primary" onClick={()=>void consent()}><Check size={16}/>{t('agree')}</button></div></div>:!active?<div className="ai-empty"><span className="ai-emblem"><Sparkles size={36}/></span><h2>{t('aiPrivate')}</h2><p>{t('aiHint')}</p><button className="primary" onClick={()=>void create()}><Plus size={16}/>{t('newAi')}</button></div>:<><div className="ai-messages">{loadingMessages?<Spinner/>:messages.map(m=><article key={m.id} className={'ai-message '+m.role+' '+(m.status==='streaming'?'streaming':'')}><div className="message-meta"><strong>{m.role==='assistant'?t('assistant'):t('you')}</strong>{m.model&&<span>{m.model}</span>}<IconButton label={t('copy')} onClick={()=>void navigator.clipboard.writeText(m.content??'')}><Copy size={13}/></IconButton></div>{m.role==='assistant'?<ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml>{m.content??(m.status==='failed'?t(m.error_code??'error'):'…')}</ReactMarkdown>:m.content}{m.status==='failed'&&<button className="text-button" onClick={()=>setDraft(messages.filter(x=>x.role==='user'&&x.seq<m.seq).at(-1)?.content??'')}>{t('retry')}</button>}</article>)}<div ref={bottom}/></div><div className="composer-area"><div className="composer"><textarea aria-label={t('askAi')} placeholder={navigator.onLine?t('askAi'):t('aiOffline')} disabled={!navigator.onLine||busy} value={draft} maxLength={status.limits.max_message_chars} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div className="composer-toolbar"><span className="character-count">{draft.length?draft.length+'/'+status.limits.max_message_chars:''}</span>{messages.some(m=>['pending','streaming'].includes(m.status))?<button className="send-button" onClick={async()=>{const current=messages.find(m=>['pending','streaming'].includes(m.status));if(current)try{await api.post('/ai/messages/'+current.id+'/cancel');refresh();}catch(e){report(e);}}}><Square size={15}/>{t('stop')}</button>:<button className="send-button" disabled={!draft.trim()||busy} onClick={()=>void send()}><Send size={17}/></button>}</div></div><div className="ai-footer">{t('aiConsent')}</div></div></>}
 </section>{memory&&<MemoryDialog onClose={()=>setMemory(false)} report={report}/>} {deleteConversation&&<Modal title={t('delete')} onClose={()=>setDeleteConversation(null)}><p>{deleteConversation.title}</p><div className="modal-actions"><button className="secondary" onClick={()=>setDeleteConversation(null)}>{t('cancel')}</button><button className="danger-button" onClick={async()=>{try{await api.delete('/ai/conversations/'+deleteConversation.id);if(active===deleteConversation.id)setActive(null);setDeleteConversation(null);refresh();}catch(e){report(e);}}}>{t('delete')}</button></div></Modal>}</div>;
}
function MemoryDialog({onClose,report}:{onClose:()=>void;report:(error:unknown)=>void}) {
 const {t}=useTranslation();const query=useQueryClient();const [content,setContent]=useState('');const [category,setCategory]=useState<Memory['category']>('other');const {data=[]}=useQuery({queryKey:['ai','memories'],queryFn:()=>api.get<Memory[]>('/ai/memories')});const close=useCallback(onClose,[onClose]);const refresh=()=>void query.invalidateQueries({queryKey:['ai','memories']});
 return <Modal title={t('memory')} onClose={close}><p>{t('memoryHint')}</p><form onSubmit={async e=>{e.preventDefault();try{await api.post('/ai/memories',{content,category});setContent('');refresh();}catch(error){report(error);}}}><label>{t('addMemory')}<input value={content} maxLength={300} required onChange={e=>setContent(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value as Memory['category'])}><option value="profile">Profile</option><option value="preference">Preference</option><option value="project">Project</option><option value="other">Other</option></select></label><button className="primary"><Plus size={15}/>{t('remember')}</button></form><div className="memory-list">{data.length===0&&<p>{t('noMemory')}</p>}{data.map(m=><div className="memory-card" key={m.id}><span>{m.content}</span><small>{m.category}</small><IconButton label={t('delete')} onClick={async()=>{try{await api.delete('/ai/memories/'+m.id);refresh();}catch(error){report(error);}}}><X size={15}/></IconButton></div>)}</div>{data.length>0&&<button className="text-button danger" onClick={async()=>{try{await api.post('/ai/memories/clear');refresh();}catch(error){report(error);}}}>{t('clearMemory')}</button>}</Modal>;
}
