import {useState,useEffect,useCallback,lazy,Suspense} from 'react';
import {useNavigate,useLocation} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {MessageCircle,Users,Sparkles,Settings,Search,Plus,ChevronDown,ArrowRight,Globe,LogOut,Hash,Pin,Check,ArrowLeft,PanelLeftClose,ShieldCheck,Smile,Command} from 'lucide-react';
import {ApiError} from '@banana/api-client';
import type {Room,Membership,Page,User} from '@banana/shared';
import {api,useSession,login,restoreSession,acceptUser} from './state';
import {useRealtime} from './realtime';
import {Banana,Avatar,IconButton,Spinner} from './components';
import {NewRoomDialog,ProfileDialog,PasswordForm} from './dialogs';
const ChatPane=lazy(()=>import('./ChatPane').then(module=>({default:module.ChatPane})));
const AiPane=lazy(()=>import('./AiPane').then(module=>({default:module.AiPane})));
export default function App(){
 const {t,i18n}=useTranslation();const session=useSession();const navigate=useNavigate();const location=useLocation();const qc=useQueryClient();
 const [error,setError]=useState('');const [toast,setToast]=useState('');const [newRoom,setNewRoom]=useState<'group'|'dm'|null>(null);const [profile,setProfile]=useState(false);const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [switcher,setSwitcher]=useState(false);const [sidebar,setSidebar]=useState(true);
 const activeId=location.pathname.startsWith('/rooms/')?location.pathname.split('/')[2]:null;const isAi=location.pathname.startsWith('/ai');const isPeople=location.pathname==='/people';
 useEffect(()=>{void restoreSession();},[]);
 useEffect(()=>{if(session.user?.locale){void i18n.changeLanguage(session.user.locale);}},[session.user?.id]);
 useEffect(()=>{const resize=()=>{if(innerWidth>=800)setSidebar(true);else if(activeId||isAi||isPeople)setSidebar(false);};resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[activeId,isAi,isPeople]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(timer);}},[toast]);
 const report=useCallback((e:unknown)=>{setError(e instanceof ApiError?t(e.code,{defaultValue:e.message}):t('error'));},[t]);
 const {data:workspaces}=useQuery({queryKey:['workspaces'],queryFn:()=>api.get<Membership[]>('/me/workspaces'),enabled:!!session.user&&!session.user.must_change_password});
 useEffect(()=>{if(workspaces){session.setWorkspaces(workspaces);if(session.workspaceId&&!workspaces.some(w=>w.workspace.id===session.workspaceId)){if(workspaces[0]){session.selectWorkspace(workspaces[0].workspace.id);navigate('/');}else useSession.setState({workspaceId:null});}}},[workspaces]);
 const {data:roomPage,isPending,refetch}=useQuery({queryKey:['rooms',session.workspaceId,filter],queryFn:()=>api.raw<Page<Room>>('/rooms?limit=100&filter='+filter),enabled:!!session.user&&!session.user.must_change_password&&!!session.workspaceId});
 const rooms=roomPage?.data??[];const status=useRealtime(rooms);
 const {data:people}=useQuery({queryKey:['people',session.workspaceId,search],queryFn:()=>api.get<User[]>('/members?q='+encodeURIComponent(search)),enabled:!!session.workspaceId&&isPeople});
 const selected=rooms.find(r=>r.id===activeId);const filtered=rooms.filter(r=>(r.name??r.other_user?.display_name??'').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!b.pinned_at)-Number(!!a.pinned_at));
 const workspace=session.workspaces.find(w=>w.workspace.id===session.workspaceId);
 const choose=(id:string)=>{navigate('/rooms/'+id);if(innerWidth<800)setSidebar(false);setError('');};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSidebar(true);document.getElementById('room-search')?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 async function logout(){try{await api.post('/auth/logout');await api.tokens.clear();qc.clear();navigate('/');}catch(e){report(e);}}
 if(!session.ready)return <div className="boot"><div className="brand-mark"><Banana/></div><Spinner/></div>;
 if(!session.user)return <LoginPage onError={report} error={error} onSuccess={()=>setError('')}/>;
 if(session.user.must_change_password)return <div className="auth-change"><div className="brand-mark"><Banana/></div><h1>{t('changePassword')}</h1><p>{t('changePasswordHint')}</p><PasswordForm onDone={async()=>{const {user}=await api.get<{user:User}>('/me');const ws=await api.get<Membership[]>('/me/workspaces');acceptUser(user,ws);}} report={report}/>{error&&<div role="alert" className="error-banner">{error}</div>}</div>;
 return <div className="app-shell">
  <nav className="rail" aria-label="Main navigation"><button className="rail-brand" aria-label="Banana Chat home" onClick={()=>navigate('/')}><Banana size={29}/></button><div className="rail-links"><IconButton label={t('messages')} className={!isAi&&!isPeople?'active':''} onClick={()=>{navigate('/');setSidebar(true);}}><MessageCircle size={23}/></IconButton><IconButton label={t('people')} className={isPeople?'active':''} onClick={()=>navigate('/people')}><Users size={23}/></IconButton><div className="rail-divider"/><IconButton label={t('assistant')} className={isAi?'active ai-rail':'ai-rail'} onClick={()=>navigate('/ai')}><Sparkles size={23}/></IconButton></div><div className="rail-bottom"><IconButton label={t('settings')} onClick={()=>setProfile(true)}><Settings size={22}/></IconButton><button className="profile-dot" aria-label={t('profile')} onClick={()=>setProfile(true)}><Avatar name={session.user.display_name} size="small"/></button></div></nav>
  <aside className={'sidebar '+(!sidebar?'mobile-hidden':'')}>
   <div className="workspace-wrap"><button className="workspace-button" aria-expanded={switcher} onClick={()=>setSwitcher(!switcher)}><span className="workspace-symbol">{workspace?.workspace.name.charAt(0)??'B'}</span><span><strong>{workspace?.workspace.name??t('workspace')}</strong><small>{t('workspace')}</small></span><ChevronDown size={17}/></button>{switcher&&<div className="workspace-menu">{session.workspaces.map(w=><button key={w.workspace.id} onClick={()=>{session.selectWorkspace(w.workspace.id);navigate('/');setSwitcher(false);setSearch('');qc.removeQueries({queryKey:['messages']});}}><span>{w.workspace.name}</span>{w.workspace.id===session.workspaceId?<Check size={16}/>:w.unread_rooms_count>0?<b>{w.unread_rooms_count}</b>:null}</button>)}</div>}</div>
   <div className="sidebar-heading"><h1>{t(isPeople?'people':'messages')}</h1><IconButton label={t('newRoom')} className="new-room-button" onClick={()=>setNewRoom('group')}><Plus size={19}/></IconButton></div>
   <label className="search-box"><Search size={16}/><input id="room-search" placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></label>
   <button className={'ai-entry '+(isAi?'selected':'')} onClick={()=>navigate('/ai')}><span className="ai-icon"><Sparkles size={20}/></span><span><strong>{t('assistant')}</strong><small>{i18n.language==='th'?'พื้นที่สำหรับไอเดียดี ๆ':'A little help, a lot of possibility'}</small></span><span className="new-pill">AI</span></button>
   <div className="sidebar-tabs">{['all','unread','hidden'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>{setFilter(f);if(isPeople)navigate('/');}}>{t(f)}{f==='unread'&&rooms.filter(r=>r.unread_count>0).length>0&&<span>{rooms.filter(r=>r.unread_count>0).length}</span>}</button>)}</div>
   <div className="room-list">
    {isPending&&session.workspaceId?<Spinner/>:null}
    {(['group','dm'] as const).map(type=>{const list=filtered.filter(r=>r.type===type);return <section key={type}><div className="list-label"><span>{t(type==='group'?'groupRooms':'directMessages')}</span><IconButton label={t(type==='group'?'newRoom':'newConversation')} onClick={()=>setNewRoom(type)}><Plus size={14}/></IconButton></div>{list.map(r=><button key={r.id} className={'room-item '+(activeId===r.id?'selected':'')} onClick={()=>choose(r.id)}>{r.type==='group'?<span className={'room-hash '+(activeId===r.id?'yellow':'')}><Hash size={21}/></span>:<Avatar name={r.other_user?.display_name??'Former member'}/>}<span className="room-copy"><span className="room-name"><strong>{r.name??r.other_user?.display_name??t('dm')}</strong><time>{r.last_message?new Date(r.last_message.created_at).toLocaleTimeString(i18n.language,{hour:'2-digit',minute:'2-digit',hour12:false}):''}</time></span><span className="room-preview"><span>{r.last_message?.body??(r.last_message?.system_event?t('system_'+r.last_message.system_event.kind):t('welcomeRoom'))}</span>{r.pinned_at&&<Pin size={12}/>} {r.unread_count>0&&<b className="unread-badge">{r.unread_count}</b>}</span></span></button>)}</section>;})}
    {!isPending&&filtered.length===0&&<div className="sidebar-empty"><MessageCircle size={28}/><strong>{t(search?'noResults':'noRooms')}</strong><p>{t(search?'emptySearch':'noRoomsHint')}</p></div>}
    {roomPage?.meta.has_more&&<button className="text-button load-rooms" onClick={async()=>{try{const next=await api.raw<Page<Room>>('/rooms?limit=100&filter='+filter+'&cursor='+roomPage.meta.next_cursor);qc.setQueryData(['rooms',session.workspaceId,filter],{data:[...rooms,...next.data],meta:next.meta});}catch(e){report(e);}}}>{t('older')}</button>}
   </div>
   <div className="sidebar-footer"><span className={'connection-dot '+(status==='connected'?'green':'')}/><span>{status==='connected'?t('online'):status==='polling'?(i18n.language==='th'?'อัปเดตทุก 5 วินาที':'Updates every 5 seconds'):t('reconnecting')}</span><span className="footer-flower">✳</span></div>
  </aside>
  <main className="main-panel">
   {error&&<div className="error-banner" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
   <div className="mobile-top"><IconButton label={t('rooms')} onClick={()=>setSidebar(!sidebar)}><ArrowLeft size={20}/></IconButton><strong>Banana Chat</strong></div>
   <Suspense fallback={<Spinner/>}>{!session.workspaceId?<div className="empty-main"><Users size={40}/><h2>{t('noWorkspace')}</h2><button className="secondary" onClick={logout}>{t('logout')}</button></div>:isAi?<AiPane report={report}/>:isPeople?<div className="people-page"><div className="page-eyebrow">{workspace?.workspace.name}</div><h1>{t('people')}</h1><p>{t('choosePeople')}</p><div className="people-grid">{people?.map(p=><button className="person-card" key={p.id} disabled={p.id===session.user?.id} onClick={async()=>{try{const {room}=await api.post<{room:Room}>('/rooms',{type:'dm',user_id:p.id});await refetch();choose(room.id);}catch(e){report(e);}}}><Avatar name={p.display_name} size="large"/><strong>{p.display_name}</strong><span>@{p.username}</span><span className="person-action">{p.id===session.user?.id?t('you'):t('startChat')} <ArrowRight size={14}/></span></button>)}</div></div>:activeId?<ChatPane key={session.workspaceId+activeId} id={activeId} room={selected} onBack={()=>navigate('/')} report={report} toast={setToast}/>:<div className="empty-main home-welcome"><div className="welcome-art"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><div className="welcome-banana"><Banana size={85}/></div><span className="art-spark">✦</span><span className="art-dot"/><span className="art-bubble"><MessageCircle size={30}/></span></div><div className="page-eyebrow">YOUR PEOPLE. YOUR SPACE.</div><h1>{t('tagline')}</h1><p>{t('noRoomsHint')}</p><button className="primary" onClick={()=>setNewRoom('dm')}><Plus size={18}/>{t('newConversation')}<ArrowRight size={17}/></button><div className="welcome-footnote"><ShieldCheck size={15}/>{i18n.language==='th'?'พื้นที่ปลอดภัยสำหรับทีมของคุณ':'A private space for your workspace'}</div></div>}</Suspense>
  </main>
  {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
  {newRoom&&<NewRoomDialog initial={newRoom} onClose={()=>setNewRoom(null)} onCreated={r=>{setNewRoom(null);void refetch();choose(r.id);}} report={report}/>}
  {profile&&<ProfileDialog onClose={()=>setProfile(false)} onLogout={logout} report={report} toast={setToast}/>}
 </div>;
}
function LoginPage({error,onError,onSuccess}:{error:string;onError:(e:unknown)=>void;onSuccess:()=>void}){
 const {t,i18n}=useTranslation();const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);
 return <div className="login-page"><section className="login-story"><a className="wordmark" href="/"><span className="brand-mark"><Banana size={28}/></span>banana<span>chat</span></a><div className="story-content"><span className="story-label"><span/> A LITTLE SPACE. BIG POSSIBILITIES.</span><h1>Your people.<br/>Your ideas.<br/><span>Better together.</span></h1><p>A thoughtful space to connect, collaborate,<br/>and make good things happen.</p><div className="story-chat"><div className="story-message"><Avatar name="Mali"/><div><strong>Mali <small>09:41</small></strong><p>Something good is coming together ✨</p></div></div><div className="story-message second"><Avatar name="Tony"/><div><strong>Tony <small>09:42</small></strong><p>Love where this is going. Let’s do it!</p></div><span className="story-check">✓✓</span></div><div className="story-typing"><span/><span/><span/></div></div></div><div className="story-footer"><span>Made for your workspace.</span><span>✳</span><span>Built for connection.</span></div><div className="story-decoration"><Banana size={280}/></div></section><section className="login-form-section"><button className="language-toggle" onClick={()=>{const lang=i18n.language==='en'?'th':'en';void i18n.changeLanguage(lang);localStorage.setItem('banana:locale',lang);}}><Globe size={16}/>{i18n.language==='en'?'English':'ไทย'}<ChevronDown size={14}/></button><div className="login-form-wrap"><div className="hello-icon"><Smile size={30}/><span>✦</span></div><span className="page-eyebrow">YOUR WORKSPACE IS WAITING</span><h2>{t('welcome')}<span className="yellow-dot">.</span></h2><p>{t('loginSub')}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await login(username,password);onSuccess();}catch(err){onError(err);}finally{setBusy(false);}}}><label>{t('username')}<input autoComplete="username" autoFocus placeholder="e.g. tony" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>{t('password')}<input type="password" autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary login-submit" disabled={busy}>{t(busy?'signingIn':'loginButton')}<ArrowRight size={19}/></button></form><div className="login-help">{t('administrator')}</div><div className="login-secure"><ShieldCheck size={16}/><span>Private by design. Connected by you.</span></div></div><footer>© {new Date().getFullYear()} Banana Chat <span>Good things happen together.</span></footer></section></div>;
}
