import {useState,useEffect,useRef,useCallback,Fragment} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import ReactMarkdown from 'react-markdown';
import {Hash,Users,Info,Search,Send,Smile,Reply,Copy,Pencil,Trash2,CheckCheck,X,Plus,Pin,EyeOff,LogOut,ArrowDown,ChevronDown,ChevronRight,MessageCircle,Paperclip,FileText,Film} from 'lucide-react';
import type {Room,Message,Page,RoomMember,User,Attachment} from '@banana/shared';
import {MessageStore,ReadThrottle,Outbox,cacheKey} from '@banana/chat-core';
import {api,useSession} from './state';
import {Avatar,IconButton,Modal,Spinner} from './components';
import {offlineCache} from './offline';
type PendingUpload={key:string;file:File;preview:string|null;progress:number;status:'uploading'|'processing'|'ready'|'failed';attachment?:Attachment};
type SearchResult={message:Message;room:{id:string;name:string|null;type:string};highlight:string};
export function ChatPane({id,room:summary,onBack,report,toast}:{id:string;room?:Room;onBack:()=>void;report:(e:unknown)=>void;toast:(s:string)=>void}){
 const {t,i18n}=useTranslation();const {user,workspaceId}=useSession();const qc=useQueryClient();const [info,setInfo]=useState(false);const [reply,setReply]=useState<Message|null>(null);const [editing,setEditing]=useState<Message|null>(null);const [deleteMessage,setDeleteMessage]=useState<Message|null>(null);const [busy,setBusy]=useState(false);const [emoji,setEmoji]=useState(false);const [earlier,setEarlier]=useState<Message[]>([]);const [cached,setCached]=useState<Message[]>([]);const [queued,setQueued]=useState(0);const [loadingEarlier,setLoadingEarlier]=useState(false);const [hasEarlier,setHasEarlier]=useState(true);const [messageSearch,setMessageSearch]=useState<string|null>(null);const [uploads,setUploads]=useState<PendingUpload[]>([]);const fileInput=useRef<HTMLInputElement>(null);
 const draftKey=`banana:draft:${user!.id}:${workspaceId}:${id}`;const [draft,setDraft]=useState(()=>localStorage.getItem(draftKey)??'');
 const scroll=useRef<HTMLDivElement>(null);const textarea=useRef<HTMLTextAreaElement>(null);const bottom=useRef<HTMLDivElement>(null);const atBottom=useRef(true);const first=useRef(true);const [jump,setJump]=useState(false);
 const {data:detail,isError}=useQuery({queryKey:['room',workspaceId,id],queryFn:()=>api.get<{room:Room}>('/rooms/'+id)});const room=detail?.room??summary;
 const {data:page,isPending,error}=useQuery({queryKey:['messages',workspaceId,id],queryFn:()=>api.raw<Page<Message>>('/rooms/'+id+'/messages')});
 const {data:members}=useQuery({queryKey:['room-members',workspaceId,id],queryFn:()=>api.get<RoomMember[]>('/rooms/'+id+'/members')});
 const {data:searchPage,isFetching:searching}=useQuery({queryKey:['message-search',workspaceId,id,messageSearch],queryFn:()=>api.raw<Page<SearchResult>>(`/search/messages?q=${encodeURIComponent(messageSearch!)}&room_id=${id}`),enabled:!!messageSearch&&messageSearch.trim().length>=2});
 const store=new MessageStore();store.seed([...cached,...earlier,...(page?.data??[])]);const messages=store.values();const display=messageSearch&&messageSearch.trim().length>=2?(searchPage?.data.map(x=>x.message)??[]):messages;
 const refresh=()=>{void qc.invalidateQueries({queryKey:['messages',workspaceId,id]});void qc.invalidateQueries({queryKey:['rooms',workspaceId]});void qc.invalidateQueries({queryKey:['room',workspaceId,id]});void qc.invalidateQueries({queryKey:['room-members',workspaceId,id]});};
 const reader=useRef<ReadThrottle|null>(null);
 const outbox=useRef<Outbox<{body:string|null;client_message_id:string;attachment_ids:string[];reply_to_message_id?:string}>|null>(null);
 useEffect(()=>{if(!offlineCache)return;const key=cacheKey(user!.id,workspaceId!,`room:${id}:outbox`);const box=new Outbox<{body:string|null;client_message_id:string;attachment_ids:string[];reply_to_message_id?:string}>(offlineCache,key,item=>api.post('/rooms/'+item.roomId+'/messages',item.payload).then(()=>{}));outbox.current=box;const update=()=>setQueued(box.values().length);void box.load().then(async()=>{update();if(navigator.onLine){await box.flush();update();refresh();}});const online=()=>void box.flush().then(()=>{update();refresh();});window.addEventListener('online',online);return()=>{window.removeEventListener('online',online);outbox.current=null;};},[id,workspaceId,user?.id]);
 useEffect(()=>{if(!offlineCache)return;const key=cacheKey(user!.id,workspaceId!,`room:${id}:messages`);void offlineCache.read<Message[]>(key).then(value=>value&&setCached(value));},[id,workspaceId,user?.id]);
 useEffect(()=>{if(page?.data&&offlineCache)void offlineCache.write(cacheKey(user!.id,workspaceId!,`room:${id}:messages`),page.data.slice(-100));},[page?.data,id,workspaceId,user?.id]);
 useEffect(()=>{reader.current=new ReadThrottle(seq=>{void api.post('/rooms/'+id+'/read',{seq}).then(()=>{void qc.invalidateQueries({queryKey:['rooms',workspaceId]});void qc.invalidateQueries({queryKey:['workspaces']});}).catch(report);});return()=>reader.current?.dispose();},[id,workspaceId]);
 useEffect(()=>{if(!editing)localStorage.setItem(draftKey,draft);},[draft,draftKey,editing]);
 const latest=messages.at(-1)?.seq??0;
 useEffect(()=>{if(!latest)return;if(first.current||atBottom.current){bottom.current?.scrollIntoView({behavior:first.current?'instant':'smooth'});first.current=false;if(document.hasFocus()&&document.visibilityState==='visible')reader.current?.mark(latest);}else setJump(true);},[latest]);
 useEffect(()=>{const focus=()=>{if(atBottom.current&&document.visibilityState==='visible')reader.current?.mark(latest);void api.post('/me/focus',{room_id:document.visibilityState==='visible'?id:null}).catch(()=>{});};focus();const timer=setInterval(focus,20000);window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);void api.post('/me/focus',{room_id:null}).catch(()=>{});};},[id,latest]);
 async function send(){const ready=uploads.filter(x=>x.status==='ready'&&x.attachment);if((!draft.trim()&&!ready.length)||busy||uploads.some(x=>x.status==='uploading'||x.status==='processing'))return;setBusy(true);try{if(editing){await api.patch('/messages/'+editing.id,{body:draft});setEditing(null);}else {const key=draftKey+':send';let pending:{body:string;id:string}|null=null;try{pending=JSON.parse(sessionStorage.getItem(key)??'null');}catch{}const signature=draft+'|'+ready.map(x=>x.attachment!.id).join(',');const clientId=pending?.body===signature?pending.id:crypto.randomUUID();const payload={body:draft||null,client_message_id:clientId,attachment_ids:ready.map(x=>x.attachment!.id),...(reply?{reply_to_message_id:reply.id}:{})};sessionStorage.setItem(key,JSON.stringify({body:signature,id:clientId}));try{await api.post('/rooms/'+id+'/messages',payload);sessionStorage.removeItem(key);}catch(error){if(!navigator.onLine&&outbox.current){await outbox.current.enqueue({id:clientId,roomId:id,createdAt:Date.now(),payload});setQueued(outbox.current.values().length);toast(i18n.language==='th'?'เก็บข้อความไว้ส่งเมื่อออนไลน์':'Message queued for when you are online');}else throw error;}}setDraft('');localStorage.removeItem(draftKey);setReply(null);uploads.forEach(x=>{if(x.preview)URL.revokeObjectURL(x.preview);});setUploads([]);atBottom.current=true;refresh();textarea.current?.focus();}catch(e){report(e);}finally{setBusy(false);}}
 const setUpload=(key:string,change:Partial<PendingUpload>)=>setUploads(current=>current.map(x=>x.key===key?{...x,...change}:x));
 async function addFiles(files:FileList|File[]){for(const file of Array.from(files).slice(0,10-uploads.length)){const key=crypto.randomUUID();const kind=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':'file';const preview=kind==='image'?URL.createObjectURL(file):null;setUploads(current=>[...current,{key,file,preview,progress:0,status:'uploading'}]);try{const plan=await api.post<{attachment_id:string;put_url:string;headers:Record<string,string>}>('/uploads',{kind,filename:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size});await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',plan.put_url);Object.entries(plan.headers).forEach(([name,value])=>xhr.setRequestHeader(name,value));xhr.upload.onprogress=e=>{if(e.lengthComputable)setUpload(key,{progress:Math.round(e.loaded/e.total*100)});};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error('Upload failed'));xhr.onerror=()=>reject(new Error('Upload failed'));xhr.send(file);});setUpload(key,{status:'processing',progress:100});let completed=(await api.post<{attachment:Attachment}>(`/uploads/${plan.attachment_id}/complete`)).attachment;for(let attempt=0;attempt<60&&!['ready','failed'].includes(completed.status);attempt++){await new Promise(resolve=>setTimeout(resolve,1000));completed=(await api.get<{attachment:Attachment}>(`/attachments/${plan.attachment_id}`)).attachment;}if(completed.status!=='ready')throw new Error('Processing failed');setUpload(key,{status:'ready',attachment:completed});}catch(e){setUpload(key,{status:'failed'});report(e);}}}
 function removeUpload(key:string){setUploads(current=>{const item=current.find(x=>x.key===key);if(item?.preview)URL.revokeObjectURL(item.preview);return current.filter(x=>x.key!==key);});}
 const title=room?.name??room?.other_user?.display_name??t('messages');
 const time=(date:string)=>new Date(date).toLocaleTimeString(i18n.language,{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:user?.timezone??'Asia/Bangkok'});
 const day=(date:string)=>new Date(date).toLocaleDateString(i18n.language,{day:'numeric',month:'long',year:'numeric',timeZone:user?.timezone??'Asia/Bangkok'});
 if(isError||error)return <div className="empty-main"><h2>{t('noResults')}</h2><p>{t('error')}</p><button className="secondary" onClick={onBack}>{t('rooms')}</button></div>;
 return <div className="chat-layout"><section className="chat-column"><header className="chat-header"><div className="chat-title-icon">{room?.type==='dm'?<Avatar name={title}/>:<Hash size={23}/>}</div><div className="chat-title"><h1>{title}</h1><span>{room?.type==='dm'?'@'+room.other_user?.username:room?.description||t('groupHint')}</span></div><div className="header-actions"><button className="member-stack" title={t('members')} onClick={()=>setInfo(!info)}>{members?.slice(0,3).map(m=><Avatar name={m.display_name} size="small" key={m.id}/>)}<span>{room?.member_count}</span></button><div className="header-divider"/><IconButton label={t('search')} onClick={()=>setMessageSearch(messageSearch===null?'':null)}><Search size={19}/></IconButton><IconButton label={t('roomInfo')} className={info?'active':''} onClick={()=>setInfo(!info)}><Info size={20}/></IconButton></div></header>
 {messageSearch!==null&&<div className="in-room-search"><Search size={16}/><input autoFocus placeholder={t('searchMessages')} value={messageSearch} onChange={e=>setMessageSearch(e.target.value)}/>{searching&&<Spinner/>}<IconButton label={t('cancel')} onClick={()=>setMessageSearch(null)}><X size={16}/></IconButton></div>}
 <div className="chat-scroll" ref={scroll} onScroll={()=>{if(scroll.current){atBottom.current=scroll.current.scrollHeight-scroll.current.scrollTop-scroll.current.clientHeight<80;if(atBottom.current){setJump(false);if(document.hasFocus())reader.current?.mark(latest);}}}}>
 {isPending?<Spinner/>:<><div className="room-intro"><div className="intro-hash">{room?.type==='dm'?<MessageCircle size={27}/>:<Hash size={30}/>}</div><h2>{room?.type==='dm'?title:'# '+title}</h2><p>{t('welcomeRoomHint')}</p><div className="intro-rule"/></div>
 {page?.meta.has_more_before&&hasEarlier&&<button className="load-earlier" disabled={loadingEarlier} onClick={async()=>{setLoadingEarlier(true);const height=scroll.current?.scrollHeight??0;try{const older=await api.raw<Page<Message>>(`/rooms/${id}/messages?before_seq=${messages[0]?.seq}`);setEarlier([...older.data,...earlier]);setHasEarlier(!!older.meta.has_more_before);requestAnimationFrame(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight-height;});}catch(e){report(e);}finally{setLoadingEarlier(false);}}}>{t('older')}</button>}
 {display.map((m,index)=>{const previous=display[index-1];const newDay=!previous||day(previous.created_at)!==day(m.created_at);const own=m.sender?.id===user?.id;const grouped=previous?.sender?.id===m.sender?.id&&previous?.type!=='system'&&!newDay&&new Date(m.created_at).getTime()-new Date(previous.created_at).getTime()<300000;const readers=members?.filter(x=>x.id!==user?.id&&x.last_read_seq>=m.seq)??[];return <Fragment key={m.id}>{newDay&&<div className="day-divider"><span>{day(m.created_at)}</span></div>}{m.type==='system'?<div className="system-message"><span>✳</span>{t('system_'+m.system_event?.kind,{name:m.system_event?.name,defaultValue:t('system_room_created')})}<time>{time(m.created_at)}</time></div>:<article id={'message-'+m.id} className={'message-row '+(grouped?'grouped ':'')+(own?'own':'')}>
 <div className="message-avatar">{!grouped&&<Avatar name={m.sender?.display_name??'Member'}/>}</div><div className="message-content">{!grouped&&<div className="message-meta"><strong>{m.sender?.display_name}</strong>{own&&<span className="you-tag">{t('you')}</span>}<time>{time(m.created_at)}</time></div>}{m.reply_to&&<button className="message-quote" onClick={()=>document.getElementById('message-'+m.reply_to!.id)?.scrollIntoView({behavior:'smooth',block:'center'})}><Reply size={14}/><span><strong>{m.reply_to.sender?.display_name}</strong>{m.reply_to.snippet??t('deletedMessage')}</span></button>}<div className={'message-body '+(m.deleted_at?'deleted':'')}>{m.deleted_at?t('deletedMessage'):<ReactMarkdown allowedElements={['p','strong','em','code','a','br']} unwrapDisallowed skipHtml components={{a:({children,...props})=><a {...props} target="_blank" rel="noopener noreferrer">{children}</a>}}>{m.body??''}</ReactMarkdown>}{m.edited_at&&<span className="edited-label" title={day(m.edited_at)+' '+time(m.edited_at)}>({t('edited')})</span>}</div>{!m.deleted_at&&m.attachments.length>0&&<AttachmentList attachments={m.attachments}/>} {own&&m.id===messages.filter(x=>x.sender?.id===user?.id).at(-1)?.id&&readers.length>0&&<div className="read-receipt"><CheckCheck size={14}/>{t('read')}{room?.type==='group'?' '+readers.length:''}</div>}</div>
 {!m.deleted_at&&<div className="message-actions"><IconButton label={t('reply')} onClick={()=>{setReply(m);textarea.current?.focus();}}><Reply size={15}/></IconButton><IconButton label={t('copy')} onClick={()=>void navigator.clipboard.writeText(m.body??'').then(()=>toast(t('copied'))).catch(report)}><Copy size={14}/></IconButton>{own&&<IconButton label={t('edit')} onClick={()=>{setEditing(m);setDraft(m.body??'');textarea.current?.focus();}}><Pencil size={14}/></IconButton>}{(own||room?.my_role==='owner'||room?.my_role==='admin')&&<IconButton label={t('delete')} onClick={()=>setDeleteMessage(m)}><Trash2 size={14}/></IconButton>}</div>}</article>}</Fragment>;})}<div ref={bottom}/></>}
 </div>
 {jump&&<button className="jump-latest" onClick={()=>{bottom.current?.scrollIntoView({behavior:'smooth'});setJump(false);}}><ArrowDown size={16}/>{t('newMessages')}</button>}
 <div className="composer-area" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void addFiles(e.dataTransfer.files);}}>{(reply||editing)&&<div className="composer-context"><Reply size={16}/><div><strong>{editing?t('edit'):t('reply')+' '+reply?.sender?.display_name}</strong><span>{(editing??reply)?.body}</span></div><IconButton label={t('cancel')} onClick={()=>{setReply(null);if(editing){setEditing(null);setDraft(localStorage.getItem(draftKey)??'');}}}><X size={16}/></IconButton></div>}{uploads.length>0&&<div className="upload-strip">{uploads.map(item=><div className={'upload-preview '+item.status} key={item.key}>{item.preview?<img src={item.preview} alt=""/>:<span>{item.file.type.startsWith('video/')?<Film size={20}/>:<FileText size={20}/>}</span>}<div><strong>{item.file.name}</strong><small>{item.status==='uploading'?item.progress+'%':t('upload_'+item.status)}</small>{item.status==='uploading'&&<i style={{width:item.progress+'%'}}/>}</div><IconButton label={t('cancel')} onClick={()=>removeUpload(item.key)}><X size={14}/></IconButton></div>)}</div>}<div className={'composer '+(busy?'sending':'')}><textarea ref={textarea} aria-label={t('typeMessage')} placeholder={t('typeMessage')+' '+(room?.type==='group'?'#'+title:'')} value={draft} maxLength={4000} disabled={busy} onPaste={e=>{if(e.clipboardData.files.length){e.preventDefault();void addFiles(e.clipboardData.files);}}} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div className="composer-toolbar"><div className="composer-tools"><IconButton label="Emoji" onClick={()=>setEmoji(!emoji)}><Smile size={19}/></IconButton><IconButton label={t('attachFiles')} onClick={()=>fileInput.current?.click()}><Paperclip size={19}/></IconButton><input ref={fileInput} className="file-input" type="file" multiple onChange={e=>{if(e.target.files)void addFiles(e.target.files);e.target.value='';}}/><span className="format-hint"><b>B</b><i>I</i><span>&lt;/&gt;</span></span></div><span className={'character-count '+(draft.length>3900?'danger':'')}>{draft.length>3500?draft.length+'/4000':''}</span><button className="send-button" aria-label={t('send')} disabled={(!draft.trim()&&!uploads.some(x=>x.status==='ready'))||busy||uploads.some(x=>x.status==='uploading'||x.status==='processing')} onClick={()=>void send()}><Send size={18}/><ChevronDown size={12}/></button></div>{emoji&&<div className="emoji-picker">{['👋','😊','✨','🍌','🙌','💛','🎉','👍','❤️','🚀','✅','🤔'].map(x=><button key={x} onClick={()=>{setDraft(draft+x);setEmoji(false);textarea.current?.focus();}}>{x}</button>)}</div>}</div><div className="composer-foot"><span>{t('composerHint')}</span><span>Made for a little more togetherness <span className="mini-banana">✳</span></span></div></div>
 </section>{info&&room&&<RoomInfo room={room} members={members??[]} onClose={()=>setInfo(false)} onBack={onBack} refresh={refresh} report={report}/>} {deleteMessage&&<Modal title={t('delete')} onClose={()=>setDeleteMessage(null)}><p>{t('deletedMessage')} — {t('delete')}?</p><blockquote>{deleteMessage.body}</blockquote><div className="modal-actions"><button className="secondary" onClick={()=>setDeleteMessage(null)}>{t('cancel')}</button><button className="danger-button" onClick={async()=>{try{await api.delete('/messages/'+deleteMessage.id);setDeleteMessage(null);refresh();}catch(e){report(e);}}}>{t('delete')}</button></div></Modal>}</div>;
}
function AttachmentList({attachments}:{attachments:Attachment[]}){return <div className="message-attachments">{attachments.map(a=>a.kind==='image'||a.kind==='avatar'?<a className="image-attachment" href={a.urls.original} target="_blank" rel="noreferrer" key={a.id}><img src={a.urls.thumb_md??a.urls.original} alt={a.original_name}/></a>:a.kind==='video'?<video key={a.id} controls preload="metadata" poster={a.urls.poster}><source src={a.urls.original} type={a.mime_type}/></video>:<a className="file-attachment" href={a.urls.original} target="_blank" rel="noreferrer" key={a.id}><FileText size={22}/><span><strong>{a.original_name}</strong><small>{Math.max(1,Math.round(a.size_bytes/1024))} KB</small></span></a>)}</div>}
function RoomInfo({room,members,onClose,onBack,refresh,report}:{room:Room;members:RoomMember[];onClose:()=>void;onBack:()=>void;refresh:()=>void;report:(e:unknown)=>void}){
 const {t}=useTranslation();const {user,workspaceId}=useSession();const [edit,setEdit]=useState(false);const [name,setName]=useState(room.name??'');const [description,setDescription]=useState(room.description??'');const [adding,setAdding]=useState(false);const [confirm,setConfirm]=useState<'delete'|'leave'|null>(null);const [confirmText,setConfirmText]=useState('');const [selected,setSelected]=useState<string[]>([]);
 const {data:people}=useQuery({queryKey:['info-people',workspaceId],queryFn:()=>api.get<User[]>('/members'),enabled:adding});
 const manager=['owner','admin'].includes(room.my_role);const perform=async(fn:()=>Promise<unknown>)=>{try{await fn();refresh();}catch(e){report(e);}};
 const closeEdit=useCallback(()=>setEdit(false),[]);const closeAdd=useCallback(()=>setAdding(false),[]);const closeConfirm=useCallback(()=>setConfirm(null),[]);
 return <aside className="room-info"><header><h2>{t('roomInfo')}</h2><IconButton label={t('cancel')} onClick={onClose}><X size={19}/></IconButton></header><div className="room-info-hero"><div className="intro-hash"><Hash size={32}/></div><h2>{room.name??room.other_user?.display_name}</h2><span>{room.member_count} {t('members')}</span></div><div className="info-quick"><button onClick={()=>void perform(()=>api.post(`/rooms/${room.id}/${room.pinned_at?'unpin':'pin'}`))}><Pin size={18}/>{t(room.pinned_at?'unpin':'pin')}</button><button onClick={async()=>{await perform(()=>api.post(`/rooms/${room.id}/${room.hidden?'unhide':'hide'}`));onBack();}}><EyeOff size={18}/>{t(room.hidden?'unhide':'hide')}</button>{room.type==='group'&&(manager||room.settings.who_can_edit_info==='everyone')&&<button onClick={()=>setEdit(true)}><Pencil size={18}/>{t('edit')}</button>}</div><div className="info-section"><h3>{t('about')}</h3><p>{room.description||t('groupHint')}</p></div><div className="info-section"><div className="info-section-heading"><h3>{t('members')} <span>{members.length}</span></h3>{room.type==='group'&&(manager||room.settings.who_can_add_members==='everyone')&&<IconButton label={t('addMembers')} onClick={()=>setAdding(true)}><Plus size={17}/></IconButton>}</div>{members.map(m=><div className="info-member" key={m.id}><Avatar name={m.display_name} size="small"/><div><strong>{m.display_name}{m.id===user?.id?' ('+t('you')+')':''}</strong><small>{t(m.role)}</small></div>{manager&&m.role!=='owner'&&m.id!==user?.id&&<details className="member-menu"><summary aria-label={'Manage '+m.display_name}><ChevronDown size={15}/></summary><div>{room.my_role==='owner'&&<button onClick={()=>void perform(()=>api.patch(`/rooms/${room.id}/members/${m.id}`,{role:'owner'}))}>{t('transferOwner')}</button>}{(m.role==='member'||room.my_role==='owner')&&<button onClick={()=>void perform(()=>api.patch(`/rooms/${room.id}/members/${m.id}`,{role:m.role==='admin'?'member':'admin'}))}>{t(m.role==='admin'?'makeMember':'makeAdmin')}</button>}{(m.role==='member'||room.my_role==='owner')&&<button className="danger" onClick={()=>void perform(()=>api.delete(`/rooms/${room.id}/members/${m.id}`))}>{t('remove')}</button>}</div></details>}</div>)}</div>{room.type==='group'&&<div className="info-danger"><button onClick={()=>setConfirm('leave')}><LogOut size={16}/>{t('leaveRoom')}</button>{room.my_role==='owner'&&<button onClick={()=>setConfirm('delete')}><Trash2 size={16}/>{t('deleteRoom')}</button>}</div>}
 {edit&&<Modal title={t('edit')} onClose={closeEdit}><form onSubmit={async e=>{e.preventDefault();try{await api.patch('/rooms/'+room.id,{name,description});closeEdit();refresh();}catch(e){report(e);}}}><label>{t('roomName')}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('description')}<textarea maxLength={500} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="modal-actions"><button className="primary">{t('save')}</button></div></form></Modal>}
 {adding&&<Modal title={t('addMembers')} onClose={closeAdd}><div className="member-picker">{people?.filter(p=>!members.some(m=>m.id===p.id)).map(p=><button key={p.id} className="picker-person" onClick={()=>setSelected(selected.includes(p.id)?selected.filter(id=>id!==p.id):[...selected,p.id])}><Avatar name={p.display_name}/><span>{p.display_name}</span><input type="checkbox" readOnly checked={selected.includes(p.id)}/></button>)}</div><div className="modal-actions"><button className="primary" disabled={!selected.length} onClick={async()=>{try{await api.post('/rooms/'+room.id+'/members',{user_ids:selected});closeAdd();refresh();}catch(e){report(e);}}}>{t('addMembers')}</button></div></Modal>}
 {confirm&&<Modal title={t(confirm==='delete'?'deleteRoom':'leaveRoom')} onClose={closeConfirm}><p>{t(confirm==='delete'?'deleteConfirm':'leaveRoom')}</p>{confirm==='delete'&&room.member_count>10&&<label>{t('confirmName')}<input value={confirmText} onChange={e=>setConfirmText(e.target.value)}/></label>}<div className="modal-actions"><button className="secondary" onClick={closeConfirm}>{t('cancel')}</button><button className="danger-button" disabled={confirm==='delete'&&room.member_count>10&&confirmText!==room.name} onClick={async()=>{try{if(confirm==='delete')await api.delete('/rooms/'+room.id);else await api.post('/rooms/'+room.id+'/leave');closeConfirm();refresh();onBack();}catch(e){report(e);}}}>{t(confirm==='delete'?'deleteRoom':'leaveRoom')}</button></div></Modal>}
 </aside>;
}
