import {useState,useCallback} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {Users,MessageCircle,Search,Check,Plus,LogOut,ExternalLink,Monitor,Globe} from 'lucide-react';
import type {Room,User} from '@banana/shared';
import {api,useSession} from './state';
import {Modal,Avatar,Spinner} from './components';
export function NewRoomDialog({initial,onClose,onCreated,report}:{initial:'group'|'dm';onClose:()=>void;onCreated:(r:Room)=>void;report:(e:unknown)=>void}){
 const {t}=useTranslation();const {user,workspaceId}=useSession();const [type,setType]=useState(initial);const [name,setName]=useState('');const [description,setDescription]=useState('');const [search,setSearch]=useState('');const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);
 const {data,isPending}=useQuery({queryKey:['member-picker',workspaceId,search],queryFn:()=>api.get<User[]>('/members?q='+encodeURIComponent(search))});
 return <Modal title={t('newConversation')} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await api.post<{room:Room}>('/rooms',type==='dm'?{type,user_id:selected[0]}:{type,name,description,member_ids:selected});onCreated(result.room);}catch(err){report(err);}finally{setBusy(false);}}}><div className="segmented"><button type="button" className={type==='dm'?'active':''} onClick={()=>{setType('dm');setSelected([]);}}><MessageCircle size={17}/>{t('dm')}</button><button type="button" className={type==='group'?'active':''} onClick={()=>setType('group')}><Users size={17}/>{t('group')}</button></div>{type==='group'&&<><label>{t('roomName')}<input placeholder={t('roomNamePlaceholder')} maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('description')}<input maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder={t('groupHint')}/></label></>}<label>{t('choosePeople')}<div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('search')}/></div></label><div className="member-picker">{isPending?<Spinner/>:data?.filter(p=>p.id!==user?.id).map(p=><button type="button" key={p.id} className={'picker-person '+(selected.includes(p.id)?'selected':'')} onClick={()=>setSelected(type==='dm'?[p.id]:selected.includes(p.id)?selected.filter(id=>id!==p.id):[...selected,p.id])}><Avatar name={p.display_name}/><span><strong>{p.display_name}</strong><small>@{p.username}</small></span><span className="checkbox">{selected.includes(p.id)&&<Check size={14}/>}</span></button>)}</div><footer className="modal-actions"><span>{selected.length} {t('selected')}</span><button type="button" className="secondary" onClick={onClose}>{t('cancel')}</button><button className="primary" disabled={busy||(type==='dm'&&!selected.length)||(type==='group'&&!name.trim())}><Plus size={17}/>{t(type==='group'?'create':'startChat')}</button></footer></form></Modal>;
}
export function PasswordForm({onDone,report}:{onDone:()=>void|Promise<void>;report:(e:unknown)=>void}){
 const {t}=useTranslation();const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [busy,setBusy]=useState(false);
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.post('/auth/change-password',{current_password:current,new_password:next});await onDone();setCurrent('');setNext('');}catch(error){report(error);}finally{setBusy(false);}}}><label>{t('currentPassword')}<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>{t('newPassword')}<input type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} minLength={10} maxLength={128} required/></label><p className="field-hint">{t('passwordHint')}</p><button className="primary" disabled={busy}>{t('changePassword')}</button></form>;
}
export function ProfileDialog({onClose,onLogout,report,toast}:{onClose:()=>void;onLogout:()=>void;report:(e:unknown)=>void;toast:(s:string)=>void}){
 const {t,i18n}=useTranslation();const {user,setUser}=useSession();const qc=useQueryClient();const [name,setName]=useState(user!.display_name);const [locale,setLocale]=useState(user!.locale??'en');const [timezone,setTimezone]=useState(user!.timezone??'Asia/Bangkok');const [tab,setTab]=useState('profile');const [busy,setBusy]=useState(false);
 const {data:sessions}=useQuery({queryKey:['sessions'],queryFn:()=>api.get<{id:string;device:{device_name:string;platform:string};ip:string;is_current:boolean}[]>('/me/sessions'),enabled:tab==='sessions'});
 return <Modal title={t('settings')} onClose={onClose}><div className="segmented">{['profile','sessions','changePassword'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{t(x)}</button>)}</div>{tab==='profile'?<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const {user}=await api.patch<{user:User}>('/me',{display_name:name,locale,timezone});setUser(user);await i18n.changeLanguage(locale);localStorage.setItem('banana:locale',locale);toast(t('saved'));onClose();}catch(error){report(error);}finally{setBusy(false);}}}><div className="profile-card"><Avatar name={name} size="large"/><div><strong>{user?.display_name}</strong><span>@{user?.username}</span></div></div><label>{t('displayName')}<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><div className="form-row"><label>{t('language')}<select value={locale} onChange={e=>setLocale(e.target.value as 'en'|'th')}><option value="en">English</option><option value="th">ไทย</option></select></label><label>{t('timezone')}<input value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label></div><div className="modal-actions"><button className="primary" disabled={busy}>{t('save')}</button></div></form>:tab==='sessions'?<div className="sessions-list">{sessions?.map(s=><div className="session-item" key={s.id}><Monitor size={22}/><div><strong>{s.device?.device_name}</strong><small>{s.ip} · {s.is_current?t('currentDevice'):s.device?.platform}</small></div>{!s.is_current&&<button className="text-button danger" onClick={async()=>{try{await api.delete('/me/sessions/'+s.id);void qc.invalidateQueries({queryKey:['sessions']});}catch(e){report(e);}}}>{t('revoke')}</button>}</div>)}</div>:<PasswordForm report={report} onDone={()=>toast(t('saved'))}/>}<div className="profile-bottom">{user?.is_system_admin&&<a href={(import.meta.env.VITE_ADMIN_URL??'http://127.0.0.1:8000/admin')} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t('adminPanel')}</a>}<button className="text-button danger" onClick={onLogout}><LogOut size={16}/>{t('logout')}</button></div></Modal>;
}
