import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import i18n from 'i18next';
import {initReactI18next} from 'react-i18next';
import {en,th} from '@banana/shared';
import App from './App';
import './styles.css';
if('serviceWorker' in navigator)void navigator.serviceWorker.register('/sw.js');
i18n.use(initReactI18next).init({resources:{en:{translation:en},th:{translation:th}},lng:localStorage.getItem('banana:locale')??(navigator.language.startsWith('th')?'th':'en'),fallbackLng:'en',interpolation:{escapeValue:false}});
export const queryClient=new QueryClient({defaultOptions:{queries:{retry:1,refetchOnWindowFocus:true,staleTime:10000}}});
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></React.StrictMode>);
