import {describe,it,expect,vi} from 'vitest';
import {MessageStore,ReadThrottle,AiStreamStore,AttachmentUrlRefresher,Outbox,PresenceStore,TypingStore,workspaceUnread,reconnectDelay} from './index';
import {TokenManager} from '@banana/api-client';
import type {Message,AiMessage,Room,Tokens} from '@banana/shared';
const msg=(seq:number):Message=>({id:`m${seq}`,seq,room_id:'r',body:`Hello ${seq}`,sender:null,attachments:[],type:'text',client_message_id:`c${seq}`,created_at:'2026-09-06T00:00:00Z',edited_at:null,edit_count:0,deleted_at:null,delete_reason:null,system_event:null,reply_to:null});
describe('FR-MSG-009 / chat-core',()=>{
 it('TC-CORE-001_002 inserts in order and deduplicates',()=>{const s=new MessageStore();s.seed([msg(2),msg(1)]);s.apply(msg(2));expect(s.values().map(m=>m.seq)).toEqual([1,2]);});
 it('TC-CORE-004_005 holds a gap until missing messages arrive',()=>{const fill=vi.fn();const s=new MessageStore(fill);s.seed([msg(10)]);s.apply(msg(12));expect(s.values().map(m=>m.seq)).toEqual([10]);expect(fill).toHaveBeenCalledWith(10);s.apply(msg(11));expect(s.values().map(m=>m.seq)).toEqual([10,11,12]);});
 it('TC-CORE-007_008 updates and preserves tombstones',()=>{const s=new MessageStore();s.seed([msg(1)]);s.apply({...msg(1),body:'Edited'});s.remove('m1','2026-09-06','sender');expect(s.values()[0]).toMatchObject({body:null,seq:1,delete_reason:'sender'});});
 it('TC-CORE-010 excludes muted rooms',()=>{const r={unread_count:2,notification:{mode:'all',muted_until:null}} as Room;expect(workspaceUnread([r,{...r,notification:{mode:'none',muted_until:null}}])).toBe(1);});
 it('TC-CORE-012 throttles maximum read cursor',()=>{vi.useFakeTimers();const send=vi.fn();const t=new ReadThrottle(send);t.mark(5);t.mark(3);t.mark(8);vi.advanceTimersByTime(1000);expect(send).toHaveBeenCalledExactlyOnceWith(8);t.dispose();vi.useRealTimers();});
 it('TC-CORE-016 caps exponential reconnect delay',()=>{expect([0,1,2,9].map(n=>reconnectDelay(n,()=>0))).toEqual([1000,2000,4000,30000]);});
 it('TC-CORE-033 single-flight token refresh',async()=>{const refresh=vi.fn(async()=>({access_token:'a',refresh_token:'b',session_id:'s'} as Tokens));const t=new TokenManager({get:async()=> 'r',set:async()=>{}},refresh,()=>{});await Promise.all([t.refresh(),t.refresh(),t.refresh(),t.refresh(),t.refresh()]);expect(refresh).toHaveBeenCalledTimes(1);});
 it('TC-CORE-040_041_042 AI deltas hold gaps and completion is authoritative',()=>{const refetch=vi.fn();const s=new AiStreamStore(refetch);s.seed({id:'a',content:'',status:'pending'} as AiMessage);s.delta('a',1,'Hello');s.delta('a',3,'!');expect(s.get('a')?.content).toBe('Hello');expect(refetch).toHaveBeenCalledWith('a');s.delta('a',2,' world');expect(s.get('a')?.content).toBe('Hello world!');s.complete({id:'a',content:'Final',status:'completed'} as AiMessage);s.delta('a',4,'ignored');expect(s.get('a')?.content).toBe('Final');});
});
describe('FR-OFF/RT shared stores',()=>{
 it('TC-CORE-020_024 persists the outbox and stops in order on failure',async()=>{let stored:unknown=null;const sent:string[]=[];const cache={read:async<T>()=>stored as T|null,write:async<T>(_key:string,value:T)=>{stored=value;},clear:async()=>{stored=null;}};const outbox=new Outbox(cache,'outbox',async item=>{sent.push(item.id);if(item.id==='b')throw new Error('offline');});await outbox.enqueue({id:'a',roomId:'r',createdAt:1,payload:{body:'one'}});await outbox.enqueue({id:'b',roomId:'r',createdAt:2,payload:{body:'two'}});await outbox.enqueue({id:'c',roomId:'r',createdAt:3,payload:{body:'three'}});await outbox.flush();expect(sent).toEqual(['a','b']);expect(outbox.values().map(x=>[x.id,x.state])).toEqual([['b','failed'],['c','pending']]);});
 it('TC-CORE-035 coalesces attachment URL refresh requests',async()=>{let calls=0;const refresh=new AttachmentUrlRefresher(async()=>{calls++;return {ok:true};});await Promise.all([refresh.get('a'),refresh.get('a')]);expect(calls).toBe(1);});
 it('TC-CORE-013_018 tracks presence and expires typing users',async()=>{vi.useFakeTimers();const presence=new PresenceStore();presence.update('u',true);expect(presence.get('u').online).toBe(true);const typing=new TypingStore();typing.mark('r','u',100);expect(typing.get('r')).toEqual(['u']);await vi.advanceTimersByTimeAsync(101);expect(typing.get('r')).toEqual([]);typing.clear();vi.useRealTimers();});
});
