<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\{Schema,DB};
return new class extends Migration {
    public function up(): void {
        Schema::create('workspaces',function(Blueprint $t){$t->ulid('id')->primary();$t->string('slug',40)->unique();$t->string('name',100);$t->string('status')->default('active');$t->ulid('avatar_attachment_id')->nullable();$t->json('settings')->nullable();$t->integer('message_retention_days')->nullable();$t->integer('attachment_retention_days')->nullable();$t->timestampsTz();});
        Schema::create('workspace_members',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->foreignUlid('user_id')->constrained()->cascadeOnDelete();$t->string('role')->default('member');$t->string('status')->default('active');$t->timestampTz('joined_at');$t->timestampTz('removed_at')->nullable();$t->ulid('invited_by')->nullable();$t->timestampsTz();$t->unique(['workspace_id','user_id']);$t->index(['user_id','status']);});
        Schema::create('rooms',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->string('type');$t->string('name',100)->nullable();$t->string('description',500)->nullable();$t->ulid('avatar_attachment_id')->nullable();$t->string('dm_key',64)->nullable();$t->foreignUlid('created_by')->constrained('users');$t->foreignUlid('owner_id')->nullable()->constrained('users');$t->bigInteger('last_seq')->default(0);$t->bigInteger('last_user_seq')->default(0);$t->ulid('last_message_id')->nullable();$t->timestampTz('last_message_at')->nullable();$t->integer('member_count')->default(0);$t->json('settings')->nullable();$t->softDeletesTz();$t->timestampTz('purge_after')->nullable();$t->timestampsTz();$t->unique(['workspace_id','dm_key']);$t->index(['workspace_id','last_message_at']);});
        Schema::create('room_members',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->foreignUlid('room_id')->constrained()->cascadeOnDelete();$t->foreignUlid('user_id')->constrained();$t->string('role')->default('member');$t->bigInteger('last_read_seq')->default(0);$t->timestampTz('last_read_at')->nullable();$t->timestampTz('joined_at');$t->timestampTz('left_at')->nullable();$t->timestampTz('hidden_at')->nullable();$t->timestampTz('pinned_at')->nullable();$t->ulid('added_by')->nullable();$t->timestampsTz();$t->unique(['room_id','user_id']);$t->index(['user_id','workspace_id','left_at']);});
        Schema::create('messages',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->foreignUlid('room_id')->constrained()->cascadeOnDelete();$t->foreignUlid('sender_id')->nullable()->constrained('users');$t->bigInteger('seq');$t->string('type')->default('text');$t->text('body')->nullable();$t->uuid('client_message_id')->nullable();$t->ulid('reply_to_message_id')->nullable();$t->json('system_event')->nullable();$t->json('metadata')->nullable();$t->timestampTz('edited_at')->nullable();$t->integer('edit_count')->default(0);$t->timestampTz('deleted_at')->nullable();$t->ulid('deleted_by')->nullable();$t->string('delete_reason')->nullable();$t->timestampsTz();$t->unique(['room_id','seq']);$t->unique(['room_id','sender_id','client_message_id']);$t->index(['workspace_id','created_at']);});
        Schema::create('message_edits',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('message_id')->constrained()->cascadeOnDelete();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->text('previous_body');$t->ulid('edited_by');$t->timestampTz('edited_at');});
        Schema::create('attachments',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->foreignUlid('uploader_id')->constrained('users');$t->string('kind');$t->string('status')->default('pending');$t->string('original_name');$t->string('mime_type',127);$t->bigInteger('size_bytes');$t->string('storage_key',512);$t->string('checksum_sha256',64)->nullable();$t->integer('width')->nullable();$t->integer('height')->nullable();$t->integer('duration_ms')->nullable();$t->json('derived')->nullable();$t->timestampTz('expires_at')->nullable();$t->softDeletesTz();$t->timestampsTz();$t->index(['status','expires_at']);});
        Schema::create('message_attachments',function(Blueprint $t){$t->foreignUlid('message_id')->constrained()->cascadeOnDelete();$t->foreignUlid('attachment_id')->constrained()->cascadeOnDelete();$t->smallInteger('position')->default(0);$t->primary(['message_id','attachment_id']);$t->unique('attachment_id');});
        Schema::create('message_mentions',function(Blueprint $t){$t->foreignUlid('message_id')->constrained()->cascadeOnDelete();$t->foreignUlid('user_id')->constrained()->cascadeOnDelete();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->primary(['message_id','user_id']);});
        Schema::create('message_reactions',function(Blueprint $t){$t->foreignUlid('message_id')->constrained()->cascadeOnDelete();$t->foreignUlid('user_id')->constrained()->cascadeOnDelete();$t->string('emoji',32);$t->primary(['message_id','user_id','emoji']);});
        Schema::create('devices',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('user_id')->constrained()->cascadeOnDelete();$t->string('platform');$t->text('push_token')->nullable();$t->string('push_provider')->nullable();$t->string('app_version',20);$t->string('device_name',100);$t->string('locale',5)->default('en');$t->timestampTz('last_active_at')->nullable();$t->integer('push_failed_count')->default(0);$t->timestampTz('push_disabled_at')->nullable();$t->timestampsTz();});
        Schema::create('sessions',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('user_id')->constrained()->cascadeOnDelete();$t->foreignUlid('device_id')->nullable()->constrained();$t->string('refresh_token_hash',64)->unique();$t->string('ip',45);$t->text('user_agent');$t->timestampTz('last_used_at');$t->timestampTz('expires_at');$t->timestampTz('revoked_at')->nullable();$t->string('revoked_reason')->nullable();$t->timestampsTz();});
        Schema::create('refresh_token_history',function(Blueprint $t){$t->string('token_hash',64)->primary();$t->foreignUlid('session_id')->constrained('sessions')->cascadeOnDelete();$t->timestampTz('expires_at');});
        Schema::create('personal_access_tokens',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('session_id')->constrained('sessions')->cascadeOnDelete();$t->string('token',64)->unique();$t->timestampTz('expires_at');$t->timestampsTz();});
        Schema::create('room_notification_settings',function(Blueprint $t){$t->foreignUlid('user_id')->constrained();$t->foreignUlid('room_id')->constrained()->cascadeOnDelete();$t->foreignUlid('workspace_id')->constrained()->cascadeOnDelete();$t->string('mode')->default('all');$t->timestampTz('muted_until')->nullable();$t->primary(['user_id','room_id']);});
        Schema::create('user_notification_settings',function(Blueprint $t){$t->foreignUlid('user_id')->primary()->constrained();$t->time('dnd_start')->nullable();$t->time('dnd_end')->nullable();$t->json('dnd_days')->nullable();$t->boolean('sound')->default(true);$t->boolean('preview_in_push')->default(true);});
        Schema::create('audit_logs',function(Blueprint $t){$t->ulid('id')->primary();$t->ulid('workspace_id')->nullable();$t->ulid('actor_id')->nullable();$t->string('actor_type');$t->string('action',64)->index();$t->string('target_type',32);$t->ulid('target_id')->nullable();$t->json('context');$t->string('ip',45)->nullable();$t->timestampTz('created_at')->index();});
        Schema::create('app_settings',function(Blueprint $t){$t->string('key')->primary();$t->json('value');$t->ulid('updated_by')->nullable();$t->timestampTz('updated_at');});
        if(DB::getDriverName()==='pgsql') {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_trgm');
            DB::statement("ALTER TABLE messages ADD COLUMN body_search tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(body, ''))) STORED");
            DB::statement('CREATE INDEX messages_search ON messages USING GIN(body_search)');
            DB::statement('CREATE INDEX messages_body_trgm ON messages USING GIN(body gin_trgm_ops)');
        }
    }
    public function down():void {foreach(array_reverse(['workspaces','workspace_members','rooms','room_members','messages','message_edits','attachments','message_attachments','message_mentions','message_reactions','devices','sessions','refresh_token_history','personal_access_tokens','room_notification_settings','user_notification_settings','audit_logs','app_settings']) as $t)Schema::dropIfExists($t);}
};
